### ISSUE TITLE
Authentication does not work

### ISSUE THREAD

**Issue by str-dst** [lfcabend/mopidy-spotify-web#10]
The authtentication is not working as documented.
The Mopidy auth website does not provide the needed client_id and client_secret
https://www.mopidy.com/authenticate
if you log in the popup window just closes instantly without providing any information.
i don't know if you are the right person for this problem but i just wanted to point out that problem.

**Comment by lfcabend** [comment]
Just tested it. Seems to work for me. Using Google Chrome Version 56.0.2924.87 (64-bit) on Ubuntu.
Wat browser are you using. 

The window is supposed to close. Check behind item "2" it should have your client id and token filled in.
below the text:
Add the credentials to the spotify_web config value in your mopidy.conf file:
