### ISSUE TITLE
Authentication Problem

### ISSUE THREAD

**Issue by ghost** [lfcabend/mopidy-spotify-web#6]
When I try to start Mopidy I get the following error-message:
"Did not receive authentication token!"

how can i solve this?

**Comment by lfcabend** [comment]
Hi, what does your mopidy spotify web configuration look like?
Did you follow the steps on https://www.mopidy.com/authenticate/#spotify?
Do you have a spotify premium account?

Are you using the  Mopidy OAuth bridge, or are using obtaining the authentication token yourself?
