### ISSUE TITLE
Connection issue

### ISSUE THREAD

**Issue by ghost** [lfcabend/mopidy-spotify-web#7]
Hi there

I am using modipy with mopidy-spotify and spotmop as a web interface, on  Raspbian Jessie.
All was working great and then I noticed that the artists, tracks and albums were unavailable, and after a quick google found modify-spotify-web :)
I made sure I have the dependancies, installed modipy-spotify-web, went to https://www.mopidy.com/authenticate/#spotify and got the authentication values and put them in a [spotify-web] section of the mopidy conf file. I have premium account.

Now when I start Modipy, I get the following error.  
The web interface still works, but I still can't access artists, tracks and albums.

```
ERROR    Unhandled exception in SpotmopFrontend (urn:uuid:a95eae50-d226-4981-a8f6-4ab13e3a086c):
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 192, in _actor_loop
    self.on_start()
  File "/usr/local/lib/python2.7/dist-packages/mopidy_spotmop/frontend.py", line 46, in on_start
    self.pusher.listen(port)
  File "/usr/lib/python2.7/dist-packages/tornado/web.py", line 1687, in listen
    server.listen(port, address)
  File "/usr/lib/python2.7/dist-packages/tornado/tcpserver.py", line 117, in listen
    sockets = bind_sockets(port, address=address)
  File "/usr/lib/python2.7/dist-packages/tornado/netutil.py", line 104, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use
```

Any ideas how to remedy this?
Many thanks, 

Matt

**Comment by adamcik** [comment]
This isn't a mopidy-spotify-web issues, this is mopidy crashing due to something else already using port 6680 (or whatever you have set in the http config section). Likely you have mopidy running as a system service in the background already using the port.

**Comment by ghost** [comment]
Thankyou for the quick reply!  You were exactly right, so I have disabled the service for now - nice one!

Having fixed that, I no longer get the error above, but artists, tracks and albums are still unavailable. Where do I start to find out why? As above, I made sure I have the dependancies, installed mopidy-spotify-web, went to https://www.mopidy.com/authenticate/#spotify and got the authentication values and put them in a [spotify-web] section of the mopidy conf file. mopidy logs into spotify in online mode with no errors. I have a  premium account.

Many thanks
